import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ProviderCon from "@/components/shared/ProviderCon";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="container mx-auto" lang="en">
      <body className={inter.className}>
        <ProviderCon>
          <Navbar />
          {children}
          <Footer />
        </ProviderCon>
      </body>
    </html>
  );
}
